query getTour($tourId: String!) {
	getTour(tourId: $tourId) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		userId
		tourName
		monumentIds
		creator {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_databaseId
			_permissions
			userId
			myId
			username
			profilePictureURL
		}
		monuments {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			location
			userId
			name
			questionId
			about
			topics
			placeDetailId
			transports
			pictureURL
			user {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				myId
				username
				profilePictureURL
			}
			placeDetail {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				name
			}
			likes {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				monumentId
				user {
					_createdAt
					_updatedAt
					_collectionId
					_id
					_permissions
					_databaseId
					userId
					myId
					username
					profilePictureURL
				}
			}
			totalLikesCount
			question {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				question
				correctAnswer
				pickingAnswers
				type
			}
			liked {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				monumentId
			}
		}
	}
}
