query getExperienceWithCreatorAndHisOtherExperiences($id: String!) {
	getExperience(id: $id) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		userId
		imgSrc
		location
		user {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			myId
			username
			profilePictureURL
			experiences {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				imgSrc
				location
			}
		}
	}
}
