query getListOfExperienceCards {
	getListOfExperiences {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		userId
		imgSrc
		location
		placeDetailId
		user {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			myId
			username
			profilePictureURL
			userId
		}
		placeDetail {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			name
		}
		liked {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			experienceId
		}
		likes {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			experienceId
			user {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				myId
				username
				status
				profilePictureURL
			}
		}
	}
}
