query getListOfExperiencesWithCreator($input: ExperienceLocationInput!) {
	getListOfExperiencesByLocation(input: $input) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		userId
		imgSrc
		location
		placeDetailId
		user {
			userId
			myId
			username
			profilePictureURL
		}
	}
}
