query getAccount {
	getAccount {
		_documentId
		_createdAt
		secondsFromUserCreatedToNow
		userId
		myId
		username
		status
		emailVerification
		phoneVerification
		profilePictureURL
		prefs {
			mapRange
			termsAccepted
		}
	}
}
