query getAccountByMyIdWithExperiencesAndMonuments($myId: String!) {
	getAccountByMyId(myId: $myId) {
		_permissions
		_databaseId
		_id
		_collectionId
		_updatedAt
		_createdAt
		userId
		myId
		username
		staus
		emailVerification
		phoneVerification
		profilePictureURL
		prefs {
			location
			termsAccepted
		}
		experiences {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			imgSrc
			location
		}
		monuments {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			location
			creatorUserId
			name
			about
			pictureURL
			placeDetailId

			placeDetails {
				name
				_databaseId
				_permissions
				_id
				_collectionId
				_updatedAt
				_createdAt
			}
		}
	}
}
