query updateProfilePicture($picture: String!) {
	updateProfilePicture(picture: $picture) {
		_createdAt
		_updatedAt
		_collectionId
		_documentId
		_permissions
		_databaseId
		userId
		myId
		username
		status
		emailVerification
		phoneVerification
		profilePictureURL
		prefs {
			mapRange
			termsAccepted
		}
	}
}
