query getListOfMonumentsWithCreator($input: MonumentInput) {
	getListOfMonuments(input: $input) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		creatorUserId
		name
		about
		placeDetailId
		pictureURL
		creator {
			_createdAt
			_updatedAt
			userId
			myId
			username
			staus
			emailVerification
			phoneVerification
			profilePictureURL
		}
		details {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			name
		}
	}
}
