query getListOfMonumentCards(
	$location: LocationInput
	$topics: [Topic!]
	$transports: [Transport!]
	$name: String
	$limit: Int
) {
	getListOfMonuments(
		location: $location
		topics: $topics
		transports: $transports
		name: $name
		limit: $limit
	) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		userId
		name
		about
		topics
		placeDetailId
		pictureURL
		transports
		user {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			myId
			username
			status
			emailVerification
			phoneVerification
			profilePictureURL
		}
		placeDetail {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			name
		}
		likes {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			monumentId
			user {
				_id
				userId
				myId
				username
				profilePictureURL
			}
		}
		liked {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			monumentId
		}
	}
}
