query getListOfMonumentCardsBySearchingName($input: MonumentInputByName!) {
	getListOfMonumentsSearchByName(input: $input) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		creatorUserId
		topic
		name
		about
		placeDetailId
		pictureURL
		creator {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			myId
			username
			status
			emailVerification
			phoneVerification
			profilePictureURL
		}
		placeDetail {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			name
		}
		likes {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			monumentId
			user {
				_id
				userId
				myId
				username
				profilePictureURL
			}
		}
		liked {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			monumentId
		}
	}
}
