query getListOfMonumentsWithCreatorAndNearestExperiences($input: MonumentInput) {
	getListOfMonuments(input: $input) {
		creator {
			_permissions
			_databaseId
			_id
			_collectionId
			_updatedAt
			_createdAt
			userId
			myId
			username
			staus
			emailVerification
			phoneVerification
			profilePictureURL
			prefs {
				location
				termsAccepted
			}
		}
		placeDetails {
			name
			_databaseId
			_permissions
			_id
			_collectionId
			_updatedAt
			_createdAt
		}
		nearExperiences {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			imgSrc
			location
			placeDetailId
		}
		pictureURL
		placeDetailId
		about
		name
		location
		creatorUserId
		_databaseId
		_permissions
		_id
		_collectionId
		_updatedAt
		_createdAt
	}
}
