query getListOfMonuments($input: MonumentLocationInput) {
	getListOfMonuments(input: $input) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		creatorUserId
		name
		about
		topics
		placeDetailId
		pictureURL
	}
}
