query getMonumentCardWithConnectedExperiences($id: String!) {
	getMonument(id: $id) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		userId
		name
		about
		topics
		placeDetailId
		pictureURL
		transports
		user {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			myId
			username

			profilePictureURL
		}
		placeDetail {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			name
		}
		likes {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			monumentId
			user {
				_id
				userId
				myId
				username
				profilePictureURL
			}
		}
		liked {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			monumentId
		}
		connectedExperiences {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			userId
			pictureUrl
			location
			connectedMonumentId
			user {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				myId
				username
				profilePictureURL
			}
			likes {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				experienceId
				user {
					_createdAt
					_updatedAt
					_collectionId
					_id
					_permissions
					_databaseId
					userId
					myId
					username
					profilePictureURL
				}
			}
			liked {
				_createdAt
				_updatedAt
				_collectionId
				_id
				_permissions
				_databaseId
				userId
				experienceId
			}
		}
		questionId
		question {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			question
			correctAnswer
			pickingAnswers
			type
		}
	}
}
