query getMonument($id: String!) {
	getMonument(id: $id) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		creatorUserId
		name
		about
		placeDetailId
		pictureURL
		details {
			_createdAt
			_updatedAt
			_collectionId
			_id
			_permissions
			_databaseId
			name
		}
	}
}
