query getMonument($id: String!) {
	getMonument(id: $id) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		creatorUserId
		name
		about
		placeDetailId
		pictureURL
		placeDetails {
			name
			_databaseId
			_permissions
			_id
			_collectionId
			_updatedAt
			_createdAt
		}
	}
}
