query getListOfItemsForMap(
	$transports: [Transport!]
	$topics: [Topic!]
	$name: String
	$limit: Int
	$location: LocationInput
) {
	getListOfExperiences(location: $location) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		userId
		imgSrc
		location
		placeDetailId
	}
	getListOfMonuments(
		transports: $transports
		topics: $topics
		name: $name
		limit: $limit
		location: $location
	) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		transports
		creatorUserId
		name
		about
		topics
		placeDetailId
		pictureURL
	}
}
