query getListOfItemsForMap(
	$monument: MonumentLocationInput!
	$experience: ExperienceLocationInput!
) {
	getListOfExperiencesByLocation(input: $experience) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		userId
		imgSrc
		location
		placeDetailId
	}
	getListOfMonumentsByLocation(input: $monument) {
		_createdAt
		_updatedAt
		_collectionId
		_id
		_permissions
		_databaseId
		location
		transports
		creatorUserId
		name
		about
		topics
		placeDetailId
		pictureURL
	}
}
