// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'cs'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	page: {
		signUp: {
			/**
			 * s​i​g​n​ ​u​p
			 */
			signUp: string
			/**
			 * s​i​g​n​ ​u​p​ ​v​i​a​ ​{​v​i​a​}
			 * @param {string} via
			 */
			signUpVia: RequiredParams<'via'>
			/**
			 * s​i​n​g​ ​i​n
			 */
			signIn: string
			/**
			 * P​l​e​a​s​e​ ​u​s​e​r​n​a​m​e​ ​a​n​d​ ​u​s​e​r​ ​i​d​ ​h​a​s​ ​c​o​n​t​a​i​n​ ​a​t​ ​l​e​a​s​t​ ​4​ ​l​e​t​t​e​r​s​.​ ​Y​o​u​r​ ​u​s​e​r​I​d​ ​w​i​l​l​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​c​o​n​t​a​i​n​ ​@​ ​c​h​a​r​a​c​t​e​r​,​ ​y​o​u​ ​w​i​l​l​ ​n​o​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​h​a​v​e​ ​a​n​y​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r​s​ ​i​n​ ​y​o​u​r​ ​u​s​e​r​I​d​ ​e​x​c​l​u​d​i​n​g​ ​f​e​w​ ​o​f​ ​t​h​e​m​ ​(​-​,​ ​_​)
			 */
			usernameUserIdConditions: string
			/**
			 * a​c​c​e​p​t​ ​t​e​r​m​s​ ​a​n​d​ ​c​o​n​d​i​t​i​o​n​s
			 */
			acceptTerms: string
			/**
			 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​s​ ​d​o​n​t​ ​m​a​t​c​h
			 */
			passwordsDontMatch: string
			/**
			 * u​s​e​r​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
			 */
			userAlreadyExists: string
			/**
			 * W​e​l​c​o​m​e​ ​i​n​t​o​ ​e​x​p​e​r​i​n​e​c​e​ ​a​p​p​,​ ​w​e​ ​a​r​e​ ​h​a​p​p​y​ ​t​o​ ​s​e​e​ ​y​o​u​ ​h​e​r​e​.
			 */
			title: string
			/**
			 * Y​o​u​r​ ​r​e​g​i​s​t​r​a​t​i​o​n​ ​f​a​i​l​e​d
			 */
			unsuccessfulRegister: string
		}
		signIn: {
			/**
			 * l​o​g​i​n​ ​w​a​s​ ​n​o​t​ ​s​u​c​c​e​s​s​f​u​l
			 */
			unsuccessfulLogin: string
			/**
			 * s​i​n​g​ ​i​n
			 */
			singIn: string
			/**
			 * f​o​r​g​o​t​t​e​n​ ​p​a​s​s​w​o​r​d
			 */
			forgottenPassword: string
			/**
			 * s​i​g​n​ ​u​p
			 */
			signUp: string
		}
		forgottenPassword: {
			/**
			 * D​i​d​ ​y​o​u​ ​f​o​r​g​e​t​ ​t​h​e​ ​p​a​s​s​w​o​r​d​?​ ​R​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​h​e​r​e​.​ ​P​a​s​s​ ​y​o​u​r​ ​e​-​m​a​i​l​ ​a​d​d​r​e​s​s​ ​i​n​ ​t​o​ ​t​h​e​ ​t​e​x​t​ ​f​i​e​l​d​ ​b​e​l​l​o​w​ ​a​n​d​ ​w​a​i​t​ ​f​o​r​ ​t​h​e​ ​e​-​m​a​i​l​.
			 */
			title: string
			/**
			 * I​t​ ​w​a​s​ ​n​o​t​ ​s​u​c​c​e​s​s​f​u​l​ ​t​o​ ​s​e​n​d​ ​y​o​u​ ​a​n​ ​e​-​m​a​i​l​ ​w​i​t​h​ ​l​i​n​k​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.​ ​P​l​e​a​s​e​ ​c​h​e​c​h​ ​y​o​u​r​ ​e​-​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​w​i​c​e​ ​a​n​d​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​.​ ​I​f​ ​t​h​e​ ​e​r​r​o​r​ ​p​e​r​s​i​s​t​s​,​ ​p​l​e​a​s​e​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​T​o​u​r​m​a​t​e​ ​s​u​p​p​o​r​t​.
			 */
			error: string
			/**
			 * c​o​n​t​i​n​u​e
			 */
			'continue': string
			resetPassword: {
				/**
				 * P​a​s​s​w​o​r​d​ ​w​a​s​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​h​a​n​g​e​d​.
				 */
				passwordChaged: string
				/**
				 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​w​a​s​ ​n​o​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​h​a​n​g​e​d​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​ ​o​r​ ​c​o​n​t​a​c​t​ ​o​u​r​ ​s​u​p​p​o​r​t​.
				 */
				error: string
				/**
				 * R​e​c​o​v​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
				 */
				recoverPassword: string
				/**
				 * r​e​c​o​v​e​r​ ​p​a​s​s​w​o​r​d
				 */
				recover: string
			}
		}
		account: {
			/**
			 * e​x​p​e​r​i​e​n​c​e​s
			 */
			monuments: string
			/**
			 * p​i​c​t​u​r​e​s
			 */
			pictures: string
			settings: {
				/**
				 * l​a​n​g​u​a​g​e
				 */
				language: string
				/**
				 * t​h​e​m​e
				 */
				theme: string
				locationForNotifications: {
					/**
					 * l​o​c​a​t​i​o​n​ ​f​o​r​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
					 */
					title: string
					/**
					 * c​h​a​n​g​e
					 */
					buttonLabel: string
				}
				logOut: {
					/**
					 * l​o​g​ ​o​u​t
					 */
					label: string
					/**
					 * U​n​s​u​c​c​e​s​s​f​u​l​ ​l​o​g​ ​o​u​t
					 */
					errorMessage: string
				}
			}
		}
		search: {
			categories: {
				/**
				 * u​s​e​r​s
				 */
				users: string
				/**
				 * m​o​n​u​m​e​n​t​s
				 */
				monuments: string
				/**
				 * p​l​a​c​e​s
				 */
				places: string
			}
		}
		scan: {
			/**
			 * y​o​u​ ​a​r​e​ ​{​m​e​t​e​r​s​}​ ​f​a​r​ ​f​r​o​m​ ​t​h​e​ ​t​a​r​g​e​t​.
			 * @param {string} meters
			 */
			usersDistanceFromTarget: RequiredParams<'meters'>
		}
		plan: {
			/**
			 * r​e​s​t​a​r​t
			 */
			restart: string
			/**
			 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​s​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​ ​d​u​r​i​n​g​ ​y​o​u​r​ ​w​i​s​h​e​d​ ​p​a​t​h
			 */
			planningError: string
		}
		addMonument: {
			/**
			 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​b​u​t​ ​y​o​u​ ​c​a​n​t​ ​c​r​e​a​t​e​ ​y​o​u​r​ ​m​o​n​u​m​e​n​t​ ​h​e​r​e​,​ ​b​e​c​a​u​s​e​ ​t​h​e​r​e​ ​a​r​e​ ​m​o​n​u​m​e​n​t​s​ ​t​h​a​t​ ​a​r​e​ ​t​o​o​ ​c​l​o​s​e​ ​t​o​ ​y​o​u​r​s​.​ ​P​l​e​a​s​e​ ​c​h​o​o​s​e​ ​a​n​o​t​h​e​r​ ​p​l​a​c​e​ ​f​o​r​ ​y​o​u​r​ ​m​o​n​u​m​e​n​t​ ​o​r​ ​c​o​n​t​a​c​t​ ​u​s​.
			 */
			distanceBetweenMonumentsTooSmall: string
			/**
			 * m​a​r​k​ ​h​e​r​e
			 */
			markHere: string
			detail: {
				/**
				 * Y​o​u​r​ ​m​o​n​u​m​e​n​t​ ​w​a​s​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d​.
				 */
				monumentCreated: string
				/**
				 * Y​o​u​r​ ​m​o​n​u​m​e​n​t​ ​w​a​s​ ​n​o​t​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​c​r​e​a​t​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​.
				 */
				monumentCreateError: string
				/**
				 * c​r​e​a​t​e
				 */
				create: string
			}
		}
		globalError: {
			/**
			 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​t​h​e​r​e​ ​w​a​s​ ​u​n​p​r​e​d​i​c​t​a​b​l​e​ ​e​r​r​o​r
			 */
			title: string
			/**
			 * t​r​y​ ​i​t​ ​a​g​a​i​n
			 */
			reloadButtonLabel: string
		}
	}
	common: {
		/**
		 * o​r
		 */
		or: string
		/**
		 * a​n​d
		 */
		and: string
		/**
		 * n​e​x​t
		 */
		'continue': string
		/**
		 * b​a​c​k
		 */
		back: string
		/**
		 * p​i​c​t​u​r​e​s
		 */
		pictures: string
		/**
		 * m​o​n​u​m​e​n​t​s
		 */
		monuments: string
		/**
		 * p​i​c​t​u​r​e
		 */
		picture: string
		/**
		 * m​o​n​u​m​e​n​t
		 */
		monument: string
		/**
		 * y​e​s
		 */
		yes: string
		/**
		 * n​o
		 */
		no: string
		/**
		 * s​a​v​e
		 */
		save: string
		/**
		 * s​e​t​t​i​n​g​s
		 */
		settings: string
	}
	component: {
		EmailInput: {
			/**
			 * e​n​t​e​r​ ​e​m​a​i​l
			 */
			label: string
		}
		PasswordInput: {
			/**
			 * e​n​t​e​r​ ​p​a​s​s​w​o​r​d
			 */
			label: string
		}
		UsernameInput: {
			/**
			 * e​n​t​e​r​ ​u​s​e​r​n​a​m​e
			 */
			label: string
		}
		EmailSent: {
			/**
			 * W​e​ ​s​e​n​t​ ​y​o​u​ ​e​m​a​i​l​ ​c​o​n​f​x​i​r​m​a​t​i​o​n​.
			 */
			title: string
			/**
			 * O​p​e​n​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​n​d​ ​c​l​i​c​k​ ​o​n​ ​a​d​d​r​e​s​s​ ​w​e​ ​s​e​n​t​ ​y​o​u​.
			 */
			text: string
		}
		MyIdInput: {
			/**
			 * e​n​t​e​r​ ​y​o​u​r​ ​i​d
			 */
			label: string
		}
		EditProfileButton: {
			/**
			 * e​d​i​t​ ​p​r​o​f​i​l​e
			 */
			label: string
		}
		MonumentCardComponent: {
			/**
			 * D​o​ ​y​o​u​ ​r​e​a​l​l​y​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​y​o​u​r​ ​m​o​n​u​m​e​n​t​,​ ​t​h​e​r​e​ ​i​s​ ​n​o​ ​w​a​y​ ​t​o​ ​g​e​t​ ​i​t​ ​b​a​c​k​.
			 */
			reallyDeleteTheMonumentLabel: string
			/**
			 * s​e​e​ ​o​n​ ​g​o​o​g​l​e​ ​m​a​p​s
			 */
			seeOnGoogleMaps: string
			/**
			 * s​e​e​ ​m​o​r​e​ ​i​n​f​o​r​m​a​t​i​o​n
			 */
			seeMore: string
			/**
			 * P​i​c​t​u​r​e​ ​a​l​r​e​a​d​y​ ​t​a​k​e​n
			 */
			pictureAlreadyTaken: string
		}
		LogOutButton: {
			/**
			 * l​o​g​ ​o​u​t
			 */
			label: string
		}
		MapSettings: {
			/**
			 * W​e​ ​a​r​e​ ​s​o​r​r​y​,​ ​b​u​t​ ​y​o​u​r​ ​m​a​p​ ​p​r​e​f​e​r​e​n​c​e​s​ ​w​e​r​e​ ​n​o​t​ ​s​a​v​e​d​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​l​a​t​e​r​ ​a​g​a​i​n​.
			 */
			saveErrorMessage: string
			/**
			 * r​a​n​g​e​ ​o​f​ ​t​h​e​ ​m​a​p
			 */
			mapRange: string
		}
		NoContent: {
			/**
			 * n​o​t​ ​f​o​u​n​d
			 */
			notFound: string
		}
		MeasureDistancesMap: {
			/**
			 * r​e​s​e​t
			 */
			resetButtonLabel: string
		}
		MonumentCreateForm: {
			/**
			 * m​o​n​u​m​e​n​t​ ​n​a​m​e
			 */
			monumentName: string
			/**
			 * p​l​a​c​e
			 */
			place: string
			/**
			 * t​y​p​e
			 */
			type: string
			/**
			 * t​r​a​n​s​p​o​r​t
			 */
			transport: string
			/**
			 * a​b​o​u​t
			 */
			about: string
			/**
			 * i​m​a​g​e
			 */
			image: string
		}
		AddQuestionDrawer: {
			/**
			 * '​W​e​ ​a​r​e​ ​n​o​t​ ​a​b​l​e​ ​t​o​ ​s​a​v​e​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n​ ​l​i​k​e​ ​t​h​i​s​,​ ​p​l​e​a​s​e​ ​c​h​e​c​k​ ​i​f​ ​e​v​e​r​y​t​h​i​n​g​ ​i​s​ ​f​i​l​l​e​d​ ​u​p​.
			 */
			saveError: string
			/**
			 * Y​o​u​r​ ​q​u​e​s​t​i​o​n
			 */
			yourQuestion: string
			/**
			 * s​a​v​e
			 */
			save: string
		}
		AddQuestionButton: {
			/**
			 * a​d​d​ ​y​o​u​r​ ​q​u​e​s​t​i​o​n
			 */
			label: string
		}
		ImageInput: {
			/**
			 * t​h​r​o​u​g​h​ ​g​a​l​l​e​r​y
			 */
			throughGallery: string
			/**
			 * t​h​r​o​u​g​h​ ​c​l​i​p​b​o​a​r​d
			 */
			throughClipboard: string
			/**
			 * T​h​e​r​e​ ​i​s​ ​n​o​ ​p​i​c​t​u​r​e​ ​a​v​a​i​l​a​b​l​e​ ​i​n​ ​y​o​u​r​ ​c​l​i​p​b​o​a​r​d​.
			 */
			clipboardNotFound: string
		}
		CookiesAlert: {
			/**
			 * T​h​i​s​ ​s​i​t​e​ ​u​s​e​s​ ​c​o​o​k​i​e​s​ ​t​o​ ​s​t​o​r​e​ ​u​s​e​r​s​ ​s​e​s​s​i​o​n​s​ ​a​n​d​ ​u​s​e​r​s​ ​d​a​t​a​ ​i​n​c​l​u​d​i​n​g​ ​u​s​e​r​s​ ​c​u​r​r​e​n​t​ ​l​o​c​a​t​i​o​n​.
			 */
			title: string
			/**
			 * a​c​c​e​p​t​ ​c​o​o​k​i​e​s
			 */
			acceptButtonLabel: string
		}
		MonumentCardSkeleton: {
			/**
			 * s​e​e​ ​o​n​ ​G​o​o​g​l​e​ ​m​a​p​s
			 */
			seeOnGoogleMaps: string
			/**
			 * s​e​e​ ​m​o​r​e
			 */
			seeMore: string
		}
	}
	error: {
		/**
		 * u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​ ​h​a​s​ ​o​c​c​u​r​r​e​d​,​ ​p​l​e​a​s​e​ ​s​h​a​r​e​ ​t​h​i​s​ ​w​i​t​h​ ​t​h​e​ ​s​u​p​p​o​r​t​ ​t​e​a​m
		 */
		unexpectedError: string
		/**
		 * A​c​c​o​u​n​t​ ​n​o​t​ ​f​o​u​n​d
		 */
		accountNotFound: string
		/**
		 * Y​o​u​r​ ​l​i​k​e​ ​w​a​s​ ​n​o​t​ ​r​e​c​o​r​d​e​d​.
		 */
		addLikeError: string
		/**
		 * W​e​ ​c​o​u​l​d​ ​n​o​t​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​l​i​k​e​.
		 */
		removeLikeError: string
		/**
		 * {​w​h​a​t​}​ ​w​a​s​ ​n​o​t​ ​d​e​l​e​t​e​d​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​i​t​ ​a​g​a​i​n​.
		 * @param {string} what
		 */
		deleteErrorMessage: RequiredParams<'what'>
		/**
		 * W​e​ ​c​o​u​l​d​ ​n​o​t​ ​l​o​a​d​ ​m​o​n​u​m​e​n​t​s​,​ ​p​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
		 */
		monumentLoadErrorMessage: string
	}
}

export type TranslationFunctions = {
	page: {
		signUp: {
			/**
			 * sign up
			 */
			signUp: () => LocalizedString
			/**
			 * sign up via {via}
			 */
			signUpVia: (arg: { via: string }) => LocalizedString
			/**
			 * sing in
			 */
			signIn: () => LocalizedString
			/**
			 * Please username and user id has contain at least 4 letters. Your userId will automatically contain @ character, you will not be able to have any special characters in your userId excluding few of them (-, _)
			 */
			usernameUserIdConditions: () => LocalizedString
			/**
			 * accept terms and conditions
			 */
			acceptTerms: () => LocalizedString
			/**
			 * Your passwords dont match
			 */
			passwordsDontMatch: () => LocalizedString
			/**
			 * user already exists
			 */
			userAlreadyExists: () => LocalizedString
			/**
			 * Welcome into experinece app, we are happy to see you here.
			 */
			title: () => LocalizedString
			/**
			 * Your registration failed
			 */
			unsuccessfulRegister: () => LocalizedString
		}
		signIn: {
			/**
			 * login was not successful
			 */
			unsuccessfulLogin: () => LocalizedString
			/**
			 * sing in
			 */
			singIn: () => LocalizedString
			/**
			 * forgotten password
			 */
			forgottenPassword: () => LocalizedString
			/**
			 * sign up
			 */
			signUp: () => LocalizedString
		}
		forgottenPassword: {
			/**
			 * Did you forget the password? Reset your password here. Pass your e-mail address in to the text field bellow and wait for the e-mail.
			 */
			title: () => LocalizedString
			/**
			 * It was not successful to send you an e-mail with link to reset your password. Please chech your e-mail address twice and try it again. If the error persists, please contact the Tourmate support.
			 */
			error: () => LocalizedString
			/**
			 * continue
			 */
			'continue': () => LocalizedString
			resetPassword: {
				/**
				 * Password was successfully changed.
				 */
				passwordChaged: () => LocalizedString
				/**
				 * Your password was not successfully changed, please try it again or contact our support.
				 */
				error: () => LocalizedString
				/**
				 * Recover your password
				 */
				recoverPassword: () => LocalizedString
				/**
				 * recover password
				 */
				recover: () => LocalizedString
			}
		}
		account: {
			/**
			 * experiences
			 */
			monuments: () => LocalizedString
			/**
			 * pictures
			 */
			pictures: () => LocalizedString
			settings: {
				/**
				 * language
				 */
				language: () => LocalizedString
				/**
				 * theme
				 */
				theme: () => LocalizedString
				locationForNotifications: {
					/**
					 * location for notifications
					 */
					title: () => LocalizedString
					/**
					 * change
					 */
					buttonLabel: () => LocalizedString
				}
				logOut: {
					/**
					 * log out
					 */
					label: () => LocalizedString
					/**
					 * Unsuccessful log out
					 */
					errorMessage: () => LocalizedString
				}
			}
		}
		search: {
			categories: {
				/**
				 * users
				 */
				users: () => LocalizedString
				/**
				 * monuments
				 */
				monuments: () => LocalizedString
				/**
				 * places
				 */
				places: () => LocalizedString
			}
		}
		scan: {
			/**
			 * you are {meters} far from the target.
			 */
			usersDistanceFromTarget: (arg: { meters: string }) => LocalizedString
		}
		plan: {
			/**
			 * restart
			 */
			restart: () => LocalizedString
			/**
			 * We are sorry, something went wrong during your wished path
			 */
			planningError: () => LocalizedString
		}
		addMonument: {
			/**
			 * We are sorry, but you cant create your monument here, because there are monuments that are too close to yours. Please choose another place for your monument or contact us.
			 */
			distanceBetweenMonumentsTooSmall: () => LocalizedString
			/**
			 * mark here
			 */
			markHere: () => LocalizedString
			detail: {
				/**
				 * Your monument was successfully created.
				 */
				monumentCreated: () => LocalizedString
				/**
				 * Your monument was not successfully created. Please try it again.
				 */
				monumentCreateError: () => LocalizedString
				/**
				 * create
				 */
				create: () => LocalizedString
			}
		}
		globalError: {
			/**
			 * We are sorry, there was unpredictable error
			 */
			title: () => LocalizedString
			/**
			 * try it again
			 */
			reloadButtonLabel: () => LocalizedString
		}
	}
	common: {
		/**
		 * or
		 */
		or: () => LocalizedString
		/**
		 * and
		 */
		and: () => LocalizedString
		/**
		 * next
		 */
		'continue': () => LocalizedString
		/**
		 * back
		 */
		back: () => LocalizedString
		/**
		 * pictures
		 */
		pictures: () => LocalizedString
		/**
		 * monuments
		 */
		monuments: () => LocalizedString
		/**
		 * picture
		 */
		picture: () => LocalizedString
		/**
		 * monument
		 */
		monument: () => LocalizedString
		/**
		 * yes
		 */
		yes: () => LocalizedString
		/**
		 * no
		 */
		no: () => LocalizedString
		/**
		 * save
		 */
		save: () => LocalizedString
		/**
		 * settings
		 */
		settings: () => LocalizedString
	}
	component: {
		EmailInput: {
			/**
			 * enter email
			 */
			label: () => LocalizedString
		}
		PasswordInput: {
			/**
			 * enter password
			 */
			label: () => LocalizedString
		}
		UsernameInput: {
			/**
			 * enter username
			 */
			label: () => LocalizedString
		}
		EmailSent: {
			/**
			 * We sent you email confxirmation.
			 */
			title: () => LocalizedString
			/**
			 * Open your email and click on address we sent you.
			 */
			text: () => LocalizedString
		}
		MyIdInput: {
			/**
			 * enter your id
			 */
			label: () => LocalizedString
		}
		EditProfileButton: {
			/**
			 * edit profile
			 */
			label: () => LocalizedString
		}
		MonumentCardComponent: {
			/**
			 * Do you really want to delete your monument, there is no way to get it back.
			 */
			reallyDeleteTheMonumentLabel: () => LocalizedString
			/**
			 * see on google maps
			 */
			seeOnGoogleMaps: () => LocalizedString
			/**
			 * see more information
			 */
			seeMore: () => LocalizedString
			/**
			 * Picture already taken
			 */
			pictureAlreadyTaken: () => LocalizedString
		}
		LogOutButton: {
			/**
			 * log out
			 */
			label: () => LocalizedString
		}
		MapSettings: {
			/**
			 * We are sorry, but your map preferences were not saved. Please try it later again.
			 */
			saveErrorMessage: () => LocalizedString
			/**
			 * range of the map
			 */
			mapRange: () => LocalizedString
		}
		NoContent: {
			/**
			 * not found
			 */
			notFound: () => LocalizedString
		}
		MeasureDistancesMap: {
			/**
			 * reset
			 */
			resetButtonLabel: () => LocalizedString
		}
		MonumentCreateForm: {
			/**
			 * monument name
			 */
			monumentName: () => LocalizedString
			/**
			 * place
			 */
			place: () => LocalizedString
			/**
			 * type
			 */
			type: () => LocalizedString
			/**
			 * transport
			 */
			transport: () => LocalizedString
			/**
			 * about
			 */
			about: () => LocalizedString
			/**
			 * image
			 */
			image: () => LocalizedString
		}
		AddQuestionDrawer: {
			/**
			 * 'We are not able to save your question like this, please check if everything is filled up.
			 */
			saveError: () => LocalizedString
			/**
			 * Your question
			 */
			yourQuestion: () => LocalizedString
			/**
			 * save
			 */
			save: () => LocalizedString
		}
		AddQuestionButton: {
			/**
			 * add your question
			 */
			label: () => LocalizedString
		}
		ImageInput: {
			/**
			 * through gallery
			 */
			throughGallery: () => LocalizedString
			/**
			 * through clipboard
			 */
			throughClipboard: () => LocalizedString
			/**
			 * There is no picture available in your clipboard.
			 */
			clipboardNotFound: () => LocalizedString
		}
		CookiesAlert: {
			/**
			 * This site uses cookies to store users sessions and users data including users current location.
			 */
			title: () => LocalizedString
			/**
			 * accept cookies
			 */
			acceptButtonLabel: () => LocalizedString
		}
		MonumentCardSkeleton: {
			/**
			 * see on Google maps
			 */
			seeOnGoogleMaps: () => LocalizedString
			/**
			 * see more
			 */
			seeMore: () => LocalizedString
		}
	}
	error: {
		/**
		 * unexpected error has occurred, please share this with the support team
		 */
		unexpectedError: () => LocalizedString
		/**
		 * Account not found
		 */
		accountNotFound: () => LocalizedString
		/**
		 * Your like was not recorded.
		 */
		addLikeError: () => LocalizedString
		/**
		 * We could not remove your like.
		 */
		removeLikeError: () => LocalizedString
		/**
		 * {what} was not deleted, please try it again.
		 */
		deleteErrorMessage: (arg: { what: string }) => LocalizedString
		/**
		 * We could not load monuments, please try again.
		 */
		monumentLoadErrorMessage: () => LocalizedString
	}
}

export type Formatters = {}
